### ISSUE TITLE
need a logo

### ISSUE THREAD

**Issue by Dishpit** [DishpitDev/Slopify#10]
i'm thinking something derivative of the Shopify logo since i have personal beef with them

**Comment by HaoTurnip** [comment]
![slopify](https://github.com/user-attachments/assets/08c80d7f-51a3-4780-8733-602a86d00d69)

I didn't have a green bag sorry

**Comment by HaoTurnip** [comment]
![slopify](https://github.com/user-attachments/assets/ad916388-bbd5-4626-87bd-faa10a76d9c1)
I didn't have a green bag sorry
