### ISSUE TITLE
Burger menu navigation is broken

### ISSUE THREAD

**Issue by Nasko-5** [DishpitDev/Slopify#200]
It does not display the links anymore

![image](https://github.com/user-attachments/assets/abb620c9-7406-4a5b-bd36-f5e2df81cfe8)
![image](https://github.com/user-attachments/assets/84fa31eb-7ffe-4b6d-a181-25434c66ff2c)

**Comment by JanPawlo** [comment]
As much as I liked the burger menu, I've got no clue what's happening to it ;/.
currently it looks like this for me:
![Capture](https://github.com/user-attachments/assets/25569fb1-c799-4762-a38c-0f4eb7733a60)

**Comment by mdemore2** [comment]
Just pushed a fix in #242
