### ISSUE TITLE
Chat needs usernames locked down

### ISSUE THREAD

**Issue by Dishpit** [DishpitDev/Slopify#66]
prevents this lmao

not sure how it'd be doable given the current infra though tbh

<img width="752" alt="image" src="https://github.com/user-attachments/assets/05e827e7-71f4-4f1c-8bc5-98d0971d5233" />

**Comment by infernostars** [comment]
For now we could do it client-side, but I'll bring it up in the server repo

**Comment by infernostars** [comment]
https://github.com/KUKHUA/txttunnel/issues/1

**Comment by infernostars** [comment]
actually wait usernames are managed by the client, the hell?

**Comment by duck4i** [comment]
I'm afraid it will never be a good solution without Auth backend. We could stop duplicate names for the duration of the instance but without Auth whoever gets in first and picks one gets to keep it while the instance is up ( and gets locked out when cache gets cleared)

**Comment by infernostars** [comment]
Yeah, better than nothing I think though

**Comment by KUKHUA** [comment]
add login with github

**Comment by duck4i** [comment]
https://github.com/DishpitDev/Slopify/pull/80
