### ISSUE TITLE
what to do with the chat

### ISSUE THREAD

**Issue by infernostars** [DishpitDev/Slopify#88]
mostly for myself, but also should we just rewrite the chat system..?

**Comment by Dishpit** [comment]
yes, i'm planning to get it deployed properly w auth to prevent things like what just happened lol

**Comment by infernostars** [comment]
i will again point out that i dont think we should have a lot of auth because then its harder to get to which does limit how many people can see it [and also how many people can build against it]
unless we wanna have like, proper bot accounts?

**Comment by Dishpit** [comment]
oh yeah auth can be very minimal at best, giving an option for anon so it's freely available

**Comment by infernostars** [comment]
seems good with me then, though a formal way to have chatbots wouldn't hurt either

**Comment by alamshafil** [comment]
We can use a P2P system as opposed to a client-to-server architecture. My only issue is gonna be the moderation of the chat. Don't want this community project to get into any legal repercussions 😅

**Comment by Dishpit** [comment]
exactly; having things tied at least semi closely to a server w auth would at least allow for IP bans and such, just in case

**Comment by ItsNyoty** [comment]
add reactions to it, just like that we can upvote or put a heart under a comment 🔥

**Comment by snugwarms** [comment]
recommending rules from Harris Foster's [The Ultimate Social Media Platform](https://discord.gg/FgW8AJ7AHH)

**Comment by duck4i** [comment]
As this is not assigned to the dev team I'll give it a try. 

Currently thinking Bun hono and sqlite backend with oauth lib to Google and GitHub, and keep the current html frontend and replace tunnels with socketIO. 

That should be accessible enough for most contributors so they can keep adding features and making it a glorious mess. 

Feedback and ideas welcome.

**Comment by infernostars** [comment]
@duck4i floorb [on the discord] is also working on something so you should talk to them
