### ISSUE TITLE
Someone broke the security check and now you cannot access the website

### ISSUE THREAD

**Issue by Mazen-AG** [DishpitDev/Slopify#94]
Saj moment, sadpepe

**Comment by Mazen-AG** [comment]
@Dishpit

**Comment by Mazen-AG** [comment]
Found where it broke, it was in pull request #89 
it added give lines of code and broke the entire website
That is the funniest shit ever

**Comment by Tmpecho** [comment]
#97 I think it was just a missing comma

**Comment by Dishpit** [comment]
Closed by #97
